import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { zhCN } from "@clerk/localizations";
import { Provider } from "./Provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "实时文档",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider
			localization={zhCN}
			appearance={{
				variables: {
					fontSize: "16px",
				},
			}}
		>
			<html lang="en">
				<body
					className={
						(cn("min-h-screen"),
						`${geistSans.variable} ${geistMono.variable} antialiased`)
					}
				>
					<Provider>{children}</Provider>
				</body>
			</html>
		</ClerkProvider>
	);
}
